# Librerías

In [1]:
import numpy as np

# Función del producto matricial

In [2]:
def MatrixMul(A, B):
    fil_a = np.size(A, 0)
    fil_b = np.size(B, 0)

    col_a = np.size(A, 1)
    col_b = np.size(B, 1)

    if col_a != fil_b:
        raise Exception("No es posible multiplicarlas T~T")
    
    else:
        MatrixProd = np.empty((fil_a, col_b))
        for i in range(fil_a):
            for j in range(col_b):
                Sum = 0
                for k in range(col_a):
                    Sum += A[i][k]*B[k][j]
                MatrixProd[i][j] = Sum

        return MatrixProd
    

# Cálculo solicitado

In [3]:
A = np.array([[1, 0, 0], [5, 1, 0], [-2, 3, 1]])
B = np.array([[4, -2, 1], [0, 3, 7], [0, 0, 2]])

print(MatrixMul(A,B))

[[ 4. -2.  1.]
 [20. -7. 12.]
 [-8. 13. 21.]]
